### PR TITLE
Add profile for file-connector

### PR DESCRIPTION
**Pull request by whikloj**
Related to [FCREPO-2028](https://jira.duraspace.org/browse/FCREPO-2028)

### CODE REVIEW

**Comment by whikloj** [comment]
Requires https://github.com/fcrepo4/fcrepo4/pull/1056 and https://github.com/whikloj/fcrepo-connector-file

**Comment by acoburn** [comment]
This is great, but at some point we need to discuss the sustainability of using maven profiles for these build permutations. Or perhaps we need to discuss the purpose of webapp-plus as a project. I wonder whether an interactive build script might provide both more flexibility and better project maintainability. If only this build machinery were scriptable...

**Comment by whikloj** [comment]
Totally agree, the overlapping choices are becoming kludgy. It might be better to have a set of simple profiles that you could add to the `pom.xml`. But any mixing and matching of those profiles is up to you to figure out?

**Comment by whikloj** [comment]
Ohhhhhhhhh, I see what you did there. 👍

**Pull request merged**
