### PR TITLE
remove profile for fcrepo-connector-file, which is unmaintained

### PR DESCRIPTION
**Pull request by bcail**

### CODE REVIEW

**Comment by acoburn** [comment]
@ruebot: looks like the answer is no: https://wiki.duraspace.org/display/DSP/Contributor+License+Agreements

@bcail can you fill out an iCLA listed on that site and send it to legal@duraspace.org

**Comment by awoods** [comment]
Here is a JIRA ticket for tracking: https://jira.duraspace.org/browse/FCREPO-2371

**Comment by bcail** [comment]
Just submitted my CLA.

**Comment by awoods** [comment]
@acoburn / @ruebot : @bcail's iCLA is now on record. Feel free to proceed.

**Comment by acoburn** [comment]
Thanks @bcail!

**Pull request merged**
